version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: microfina-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    # volumes:
    #   - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: microfina-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=microfina;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Password123!
    depends_on:
      - sqlserver
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: microfina-adminer
    ports:
      - "8888:8080"
    depends_on:
      - sqlserver
    restart: unless-stopped

volumes:
  sqlserver_data: