package com.microfina.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.DynamicUpdate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Credits – root credit loan entity (JOINED inheritance).
 *
 * Represents a microfinance credit granted to a member. Subclassed by
 * {@link CreditsGroupe} for group / solidarity loans.
 *
 * Lifecycle: BROUILLON → SOUMIS → VALIDE_AGENT → VALIDE_COMITE → DEBLOQUE → SOLDE.
 * On DEBLOQUE:
 *   1. {@link Amortp} rows are generated by {@code AmortissementService}.
 *   2. A {@link Comptabilite} journal entry is posted (deblocage).
 *   3. {@link HistoriqueVisaCredit} records the transition.
 *
 * FK references:
 *   {@link Membres}             – borrowing member   (Phase 2)
 *   {@link ProduitCredit}       – credit product     (Phase 3)
 *   {@link Agence}              – issuing branch     (Phase 1)
 *   {@link ModeDeCalculInteret} – interest method    (Phase 1)
 *   {@link AgentCredit}         – loan officer       (Phase 1)
 *
 * DDL source of truth: P4-001-CREATE-TABLE-Credits.xml.
 * Spec: Phase 4, Section 8 (Mise en place de crédits).
 */
@Entity
@Table(
    name = "Credits",
    uniqueConstraints = @UniqueConstraint(
        name        = "UQ_Credits_NUMCREDIT",
        columnNames = {"NUMCREDIT"}
    )
)
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(
    name              = "DTYPE",
    discriminatorType = DiscriminatorType.STRING,
    columnDefinition  = "NVARCHAR(31)"
)
@DiscriminatorValue("Credits")
@DynamicUpdate
public class Credits implements Serializable {

    private static final long serialVersionUID = 1L;

    // ── PK ────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "IDCREDIT", nullable = false)
    private Long idCredit;

    // ── Business key ──────────────────────────────────────────────

    /** Human-readable credit reference, e.g. "CR-2024-00123". */
    @Size(max = 25)
    @Column(name = "NUMCREDIT", length = 25)
    private String numCredit;

    // ── Lifecycle status ──────────────────────────────────────────

    /**
     * Current lifecycle state. Stored as a String to keep DDL simple;
     * use {@link CreditStatut} values for all comparisons.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "STATUT", length = 20, nullable = false)
    private CreditStatut statut = CreditStatut.BROUILLON;

    // ── Amounts ───────────────────────────────────────────────────

    /** Amount requested by the member in the application. */
    @Column(name = "MONTANT_DEMANDE", precision = 19, scale = 4)
    private BigDecimal montantDemande;

    /** Amount formally approved by the credit committee. */
    @Column(name = "MONTANT_ACCORDE", precision = 19, scale = 4)
    private BigDecimal montantAccorde;

    /** Amount actually disbursed (may be less than montantAccorde). */
    @Column(name = "MONTANT_DEBLOQUER", precision = 19, scale = 4)
    private BigDecimal montantDebloquer;

    // ── Current outstanding balances (updated on each Reglement) ──

    @Column(name = "SOLDE_CAPITAL", precision = 19, scale = 4)
    private BigDecimal soldeCapital;

    @Column(name = "SOLDE_INTERET", precision = 19, scale = 4)
    private BigDecimal soldeInteret;

    @Column(name = "SOLDE_PENALITE", precision = 19, scale = 4)
    private BigDecimal soldePenalite;

    // ── Rates (snapshot at approval; may differ from product defaults) ──

    @Column(name = "TAUX_INTERET", precision = 19, scale = 4)
    private BigDecimal tauxInteret;

    @Column(name = "TAUX_PENALITE", precision = 19, scale = 4)
    private BigDecimal tauxPenalite;

    @Column(name = "TAUX_COMMISSION", precision = 19, scale = 4)
    private BigDecimal tauxCommission;

    @Column(name = "TAUX_ASSURANCE", precision = 19, scale = 4)
    private BigDecimal tauxAssurance;

    // ── Repayment schedule parameters ────────────────────────────

    /** Total loan duration (unit = PERIODICITE). */
    @Column(name = "DUREE")
    private Integer duree;

    /** Number of repayment instalments. */
    @Column(name = "NOMBRE_ECHEANCE")
    private Integer nombreEcheance;

    /** Grace period length in the same unit as PERIODICITE. */
    @Column(name = "DELAI_GRACE")
    private Integer delaiGrace;

    /**
     * Repayment frequency code.
     * See {@link ModeCalculInteretConstant} PERIODICITE_* constants.
     */
    @Size(max = 10)
    @Column(name = "PERIODICITE", length = 10)
    private String periodicite;

    // ── Key dates ─────────────────────────────────────────────────

    @Column(name = "DATE_DEMANDE")
    private LocalDate dateDemande;

    @Column(name = "DATE_ACCORD")
    private LocalDate dateAccord;

    /** Date funds were released to the member (triggers Amortp generation). */
    @Column(name = "DATE_DEBLOCAGE")
    private LocalDate dateDeblocage;

    @Column(name = "DATE_PREMIERE_ECHEANCE")
    private LocalDate datePremièreEcheance;

    /** Final instalment due date. */
    @Column(name = "DATE_ECHEANCE")
    private LocalDate dateEcheance;

    /** Date the credit was fully settled or written off. */
    @Column(name = "DATE_CLOTURE")
    private LocalDate dateCloture;

    // ── Classification ────────────────────────────────────────────

    @Size(max = 255)
    @Column(name = "OBJET_CREDIT", length = 255)
    private String objetCredit;

    @Size(max = 50)
    @Column(name = "CODE_OBJET_CREDIT", length = 50)
    private String codeObjetCredit;

    /** Cycle number for progressive / solidarity group lending. */
    @Column(name = "NUMEROCYCLE")
    private Integer numeroCycle;

    /** Rank within the member's credit history for this product. */
    @Column(name = "RANG_CREDIT")
    private Integer rangCredit;

    // ── Accounting ────────────────────────────────────────────────

    @Size(max = 30)
    @Column(name = "COMPTE_COMPTABLE", length = 30)
    private String compteComptable;

    /** 1 = accounting breakdown has been verified by the accountant. */
    @Column(name = "DETAILOK")
    private Integer detailOk = 0;

    // ── Phase 12 — Workflow étape courante ────────────────────────

    @Column(name = "etape_courante", length = 30, nullable = false)
    private String etapeCourante = "SAISIE";

    // ── Audit ─────────────────────────────────────────────────────

    @Size(max = 48)
    @Column(name = "utilisateur", length = 48)
    private String utilisateur;

    // ── Optimistic lock ───────────────────────────────────────────

    @Version
    @Column(name = "VERSION")
    private Integer version = 0;

    // ── FK associations ───────────────────────────────────────────

    /**
     * Borrowing member (Phase 2).
     * FK to membres(NUM_MEMBRE).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "nummembre",
        referencedColumnName = "NUM_MEMBRE",
        foreignKey           = @ForeignKey(name = "FK_Credits_membres")
    )
    private Membres membre;

    /**
     * Credit product that governs rates and schedule (Phase 3).
     * FK to produitcredit(NUMPRODUIT).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "numproduit",
        referencedColumnName = "NUMPRODUIT",
        foreignKey           = @ForeignKey(name = "FK_Credits_produitcredit")
    )
    private ProduitCredit produitCredit;

    /**
     * Branch where the credit was issued (Phase 1).
     * FK to AGENCE(CODE_AGENCE).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "agence",
        referencedColumnName = "CODE_AGENCE",
        foreignKey           = @ForeignKey(name = "FK_Credits_AGENCE")
    )
    private Agence agence;

    /**
     * Interest calculation mode snapshot (Phase 1).
     * FK to mode_de_calcul_interet(CODEMODE).
     * Determines the algorithm used in {@code AmortissementService}.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "codemode",
        referencedColumnName = "CODEMODE",
        foreignKey           = @ForeignKey(name = "FK_Credits_mode_de_calcul_interet")
    )
    private ModeDeCalculInteret modeDeCalculInteret;

    /**
     * Responsible loan officer (Phase 1).
     * FK to AGENT_CREDIT(IDAGENTCREDIT).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "agentcredit",
        referencedColumnName = "CODE_AGENT",
        foreignKey           = @ForeignKey(name = "FK_Credits_AgentCredit")
    )
    private AgentCredit agentCredit;

    // ── Generated (was Lombok) ──────────────────────────────────────────────

    public Credits() {
    }

    public Credits(Long idCredit, String numCredit, CreditStatut statut, BigDecimal montantDemande, BigDecimal montantAccorde, BigDecimal montantDebloquer, BigDecimal soldeCapital, BigDecimal soldeInteret, BigDecimal soldePenalite, BigDecimal tauxInteret, BigDecimal tauxPenalite, BigDecimal tauxCommission, BigDecimal tauxAssurance, Integer duree, Integer nombreEcheance, Integer delaiGrace, String periodicite, LocalDate dateDemande, LocalDate dateAccord, LocalDate dateDeblocage, LocalDate datePremièreEcheance, LocalDate dateEcheance, LocalDate dateCloture, String objetCredit, String codeObjetCredit, Integer numeroCycle, Integer rangCredit, String compteComptable, Integer detailOk, String utilisateur, Integer version, Membres membre, ProduitCredit produitCredit, Agence agence, ModeDeCalculInteret modeDeCalculInteret, AgentCredit agentCredit) {
        this.idCredit = idCredit;
        this.numCredit = numCredit;
        this.statut = statut;
        this.montantDemande = montantDemande;
        this.montantAccorde = montantAccorde;
        this.montantDebloquer = montantDebloquer;
        this.soldeCapital = soldeCapital;
        this.soldeInteret = soldeInteret;
        this.soldePenalite = soldePenalite;
        this.tauxInteret = tauxInteret;
        this.tauxPenalite = tauxPenalite;
        this.tauxCommission = tauxCommission;
        this.tauxAssurance = tauxAssurance;
        this.duree = duree;
        this.nombreEcheance = nombreEcheance;
        this.delaiGrace = delaiGrace;
        this.periodicite = periodicite;
        this.dateDemande = dateDemande;
        this.dateAccord = dateAccord;
        this.dateDeblocage = dateDeblocage;
        this.datePremièreEcheance = datePremièreEcheance;
        this.dateEcheance = dateEcheance;
        this.dateCloture = dateCloture;
        this.objetCredit = objetCredit;
        this.codeObjetCredit = codeObjetCredit;
        this.numeroCycle = numeroCycle;
        this.rangCredit = rangCredit;
        this.compteComptable = compteComptable;
        this.detailOk = detailOk;
        this.utilisateur = utilisateur;
        this.version = version;
        this.membre = membre;
        this.produitCredit = produitCredit;
        this.agence = agence;
        this.modeDeCalculInteret = modeDeCalculInteret;
        this.agentCredit = agentCredit;
    }

    public Long getIdCredit() {
        return idCredit;
    }

    public void setIdCredit(Long idCredit) {
        this.idCredit = idCredit;
    }

    public String getNumCredit() {
        return numCredit;
    }

    public void setNumCredit(String numCredit) {
        this.numCredit = numCredit;
    }

    public CreditStatut getStatut() {
        return statut;
    }

    public void setStatut(CreditStatut statut) {
        this.statut = statut;
    }

    public BigDecimal getMontantDemande() {
        return montantDemande;
    }

    public void setMontantDemande(BigDecimal montantDemande) {
        this.montantDemande = montantDemande;
    }

    public BigDecimal getMontantAccorde() {
        return montantAccorde;
    }

    public void setMontantAccorde(BigDecimal montantAccorde) {
        this.montantAccorde = montantAccorde;
    }

    public BigDecimal getMontantDebloquer() {
        return montantDebloquer;
    }

    public void setMontantDebloquer(BigDecimal montantDebloquer) {
        this.montantDebloquer = montantDebloquer;
    }

    public BigDecimal getSoldeCapital() {
        return soldeCapital;
    }

    public void setSoldeCapital(BigDecimal soldeCapital) {
        this.soldeCapital = soldeCapital;
    }

    public BigDecimal getSoldeInteret() {
        return soldeInteret;
    }

    public void setSoldeInteret(BigDecimal soldeInteret) {
        this.soldeInteret = soldeInteret;
    }

    public BigDecimal getSoldePenalite() {
        return soldePenalite;
    }

    public void setSoldePenalite(BigDecimal soldePenalite) {
        this.soldePenalite = soldePenalite;
    }

    public BigDecimal getTauxInteret() {
        return tauxInteret;
    }

    public void setTauxInteret(BigDecimal tauxInteret) {
        this.tauxInteret = tauxInteret;
    }

    public BigDecimal getTauxPenalite() {
        return tauxPenalite;
    }

    public void setTauxPenalite(BigDecimal tauxPenalite) {
        this.tauxPenalite = tauxPenalite;
    }

    public BigDecimal getTauxCommission() {
        return tauxCommission;
    }

    public void setTauxCommission(BigDecimal tauxCommission) {
        this.tauxCommission = tauxCommission;
    }

    public BigDecimal getTauxAssurance() {
        return tauxAssurance;
    }

    public void setTauxAssurance(BigDecimal tauxAssurance) {
        this.tauxAssurance = tauxAssurance;
    }

    public Integer getDuree() {
        return duree;
    }

    public void setDuree(Integer duree) {
        this.duree = duree;
    }

    public Integer getNombreEcheance() {
        return nombreEcheance;
    }

    public void setNombreEcheance(Integer nombreEcheance) {
        this.nombreEcheance = nombreEcheance;
    }

    public Integer getDelaiGrace() {
        return delaiGrace;
    }

    public void setDelaiGrace(Integer delaiGrace) {
        this.delaiGrace = delaiGrace;
    }

    public String getPeriodicite() {
        return periodicite;
    }

    public void setPeriodicite(String periodicite) {
        this.periodicite = periodicite;
    }

    public LocalDate getDateDemande() {
        return dateDemande;
    }

    public void setDateDemande(LocalDate dateDemande) {
        this.dateDemande = dateDemande;
    }

    public LocalDate getDateAccord() {
        return dateAccord;
    }

    public void setDateAccord(LocalDate dateAccord) {
        this.dateAccord = dateAccord;
    }

    public LocalDate getDateDeblocage() {
        return dateDeblocage;
    }

    public void setDateDeblocage(LocalDate dateDeblocage) {
        this.dateDeblocage = dateDeblocage;
    }

    public LocalDate getDatePremièreEcheance() {
        return datePremièreEcheance;
    }

    public void setDatePremièreEcheance(LocalDate datePremièreEcheance) {
        this.datePremièreEcheance = datePremièreEcheance;
    }

    public LocalDate getDateEcheance() {
        return dateEcheance;
    }

    public void setDateEcheance(LocalDate dateEcheance) {
        this.dateEcheance = dateEcheance;
    }

    public LocalDate getDateCloture() {
        return dateCloture;
    }

    public void setDateCloture(LocalDate dateCloture) {
        this.dateCloture = dateCloture;
    }

    public String getObjetCredit() {
        return objetCredit;
    }

    public void setObjetCredit(String objetCredit) {
        this.objetCredit = objetCredit;
    }

    public String getCodeObjetCredit() {
        return codeObjetCredit;
    }

    public void setCodeObjetCredit(String codeObjetCredit) {
        this.codeObjetCredit = codeObjetCredit;
    }

    public Integer getNumeroCycle() {
        return numeroCycle;
    }

    public void setNumeroCycle(Integer numeroCycle) {
        this.numeroCycle = numeroCycle;
    }

    public Integer getRangCredit() {
        return rangCredit;
    }

    public void setRangCredit(Integer rangCredit) {
        this.rangCredit = rangCredit;
    }

    public String getCompteComptable() {
        return compteComptable;
    }

    public void setCompteComptable(String compteComptable) {
        this.compteComptable = compteComptable;
    }

    public Integer getDetailOk() {
        return detailOk;
    }

    public void setDetailOk(Integer detailOk) {
        this.detailOk = detailOk;
    }

    public String getUtilisateur() {
        return utilisateur;
    }

    public void setUtilisateur(String utilisateur) {
        this.utilisateur = utilisateur;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Membres getMembre() {
        return membre;
    }

    public void setMembre(Membres membre) {
        this.membre = membre;
    }

    public ProduitCredit getProduitCredit() {
        return produitCredit;
    }

    public void setProduitCredit(ProduitCredit produitCredit) {
        this.produitCredit = produitCredit;
    }

    public Agence getAgence() {
        return agence;
    }

    public void setAgence(Agence agence) {
        this.agence = agence;
    }

    public ModeDeCalculInteret getModeDeCalculInteret() {
        return modeDeCalculInteret;
    }

    public void setModeDeCalculInteret(ModeDeCalculInteret modeDeCalculInteret) {
        this.modeDeCalculInteret = modeDeCalculInteret;
    }

    public AgentCredit getAgentCredit() {
        return agentCredit;
    }

    public void setAgentCredit(AgentCredit agentCredit) {
        this.agentCredit = agentCredit;
    }

    public String getEtapeCourante() {
        return etapeCourante;
    }

    public void setEtapeCourante(String etapeCourante) {
        this.etapeCourante = etapeCourante;
    }

    @Override
    public String toString() {
        return "Credits("
            + "idCredit=" + idCredit
            + ", numCredit=" + numCredit
            + ")";
    }
}
