spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=microfina;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Sql@Server2024

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml