spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=microfina;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml