package com.microfina.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.DynamicUpdate;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Amortp – amortization schedule row (tableau d'amortissement).
 *
 * THE central table for the credit repayment flow.
 *
 * One row per scheduled instalment per credit, generated by
 * {@link com.microfina.service.AmortissementService} at disbursement time.
 * Each row is updated in-place as {@link Reglement} / {@link DetailReglement}
 * rows are posted against it.
 *
 * Unique constraint: one row per (idcredit, NUMECHEANCE).
 *
 * Scheduled amounts (CAPITAL, INTERET, PENALITE, ASSURANCE, COMMISSION)
 * are all DECIMAL(19,4) and are set at row-generation time.
 * Settled amounts (*_REMBOURSE / *_REGLEE) are initialised to 0 and
 * incremented as payments arrive.
 *
 * STATUT_ECHEANCE lifecycle:
 *   EN_ATTENTE → EN_RETARD (past due) → PARTIELLEMENT_REGLE → REGLE
 *
 * DDL source of truth: P4-005-CREATE-TABLE-Amortp.xml.
 * Spec: Phase 4, Section 10 (tableau d'amortissement).
 */
@Entity
@Table(
    name = "Amortp",
    uniqueConstraints = @UniqueConstraint(
        name        = "UQ_Amortp_credit_echeance",
        columnNames = {"idcredit", "NUMECHEANCE"}
    )
)
@DynamicUpdate
public class Amortp implements Serializable {

    private static final long serialVersionUID = 1L;

    // ── PK ────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "IDAMORTP", nullable = false)
    private Long idAmortp;

    // ── Instalment identity ───────────────────────────────────────

    /** Sequential instalment number (1 = first, N = last). */
    @Column(name = "NUMECHEANCE", nullable = false)
    private Integer numEcheance;

    /** Scheduled due date for this instalment. */
    @Column(name = "DATE_ECHEANCE")
    private LocalDate dateEcheance;

    /** Actual payment date (null until fully settled). */
    @Column(name = "DATE_REGLEMENT")
    private LocalDate dateReglement;

    // ── Scheduled amounts (DECIMAL 19,4 – set at generation) ──────

    /** Principal portion due this period. */
    @Column(name = "CAPITAL", precision = 19, scale = 4, nullable = false)
    private BigDecimal capital;

    /** Interest portion due this period. */
    @Column(name = "INTERET", precision = 19, scale = 4, nullable = false)
    private BigDecimal interet;

    /** Late-payment penalties accrued on this instalment. */
    @Column(name = "PENALITE", precision = 19, scale = 4, nullable = false)
    private BigDecimal penalite = BigDecimal.ZERO;

    /** Insurance premium portion due this period. */
    @Column(name = "ASSURANCE", precision = 19, scale = 4, nullable = false)
    private BigDecimal assurance = BigDecimal.ZERO;

    /** Commission portion due this period. */
    @Column(name = "COMMISSION", precision = 19, scale = 4, nullable = false)
    private BigDecimal commission = BigDecimal.ZERO;

    /**
     * Tax (e.g. TVA / VAT) charged on interest and fees for this period.
     * Required by Mauritanian fiscal regulations.
     */
    @Column(name = "TAXE", precision = 19, scale = 4, nullable = false)
    private BigDecimal taxe = BigDecimal.ZERO;

    /** Sum of CAPITAL + INTERET + PENALITE + ASSURANCE + COMMISSION + TAXE. */
    @Column(name = "TOTAL_ECHEANCE", precision = 19, scale = 4, nullable = false)
    private BigDecimal totalEcheance;

    /** Declining principal balance after this instalment (DEGRESSIF method). */
    @Column(name = "SOLDE_CAPITAL", precision = 19, scale = 4)
    private BigDecimal soldeCapital;

    // ── Amounts actually settled (incremented by DetailReglement) ──

    @Column(name = "CAPITAL_REMBOURSE", precision = 19, scale = 4, nullable = false)
    private BigDecimal capitalRembourse = BigDecimal.ZERO;

    @Column(name = "INTERET_REMBOURSE", precision = 19, scale = 4, nullable = false)
    private BigDecimal interetRembourse = BigDecimal.ZERO;

    @Column(name = "PENALITE_REGLEE", precision = 19, scale = 4, nullable = false)
    private BigDecimal penaliteReglee = BigDecimal.ZERO;

    @Column(name = "ASSURANCE_REGLEE", precision = 19, scale = 4, nullable = false)
    private BigDecimal assuranceReglee = BigDecimal.ZERO;

    @Column(name = "COMMISSION_REGLEE", precision = 19, scale = 4, nullable = false)
    private BigDecimal commissionReglee = BigDecimal.ZERO;

    /** Portion of TAXE actually settled by payments received so far. */
    @Column(name = "TAXE_REGLEE", precision = 19, scale = 4, nullable = false)
    private BigDecimal taxeReglee = BigDecimal.ZERO;

    // ── Instalment status ─────────────────────────────────────────

    /**
     * EN_ATTENTE           – not yet due or awaiting payment
     * EN_RETARD            – past due date, not yet settled
     * PARTIELLEMENT_REGLE  – partial payment received
     * REGLE                – fully settled
     */
    @Column(name = "STATUT_ECHEANCE", length = 25, nullable = false)
    private String statutEcheance = "EN_ATTENTE";

    // ── Optimistic lock ───────────────────────────────────────────

    @Version
    @Column(name = "VERSION")
    private Integer version = 0;

    // ── FK ────────────────────────────────────────────────────────

    /**
     * The credit this instalment belongs to.
     * FK to Credits(IDCREDIT).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name                 = "idcredit",
        referencedColumnName = "IDCREDIT",
        foreignKey           = @ForeignKey(name = "FK_Amortp_Credits")
    )
    private Credits credit;

    // ── Computed helpers ──────────────────────────────────────────

    /**
     * Returns the remaining principal not yet repaid for this instalment.
     * Convenience method used by the payment-allocation logic.
     */
    public BigDecimal getCapitalRestant() {
        return capital.subtract(capitalRembourse);
    }

    /**
     * Returns the remaining interest not yet repaid for this instalment.
     */
    public BigDecimal getInteretRestant() {
        return interet.subtract(interetRembourse);
    }

    /** Returns the portion of tax not yet settled. */
    public BigDecimal getTaxeRestante() {
        return taxe.subtract(taxeReglee);
    }

    /**
     * Returns true if this instalment has been completely settled.
     */
    public boolean isRegle() {
        return "REGLE".equals(statutEcheance);
    }

    // ── Generated (was Lombok) ──────────────────────────────────────────────

    public Amortp() {
    }

    public Amortp(Long idAmortp, Integer numEcheance, LocalDate dateEcheance, LocalDate dateReglement, BigDecimal capital, BigDecimal interet, BigDecimal penalite, BigDecimal assurance, BigDecimal commission, BigDecimal taxe, BigDecimal totalEcheance, BigDecimal soldeCapital, BigDecimal capitalRembourse, BigDecimal interetRembourse, BigDecimal penaliteReglee, BigDecimal assuranceReglee, BigDecimal commissionReglee, BigDecimal taxeReglee, String statutEcheance, Integer version, Credits credit) {
        this.idAmortp = idAmortp;
        this.numEcheance = numEcheance;
        this.dateEcheance = dateEcheance;
        this.dateReglement = dateReglement;
        this.capital = capital;
        this.interet = interet;
        this.penalite = penalite;
        this.assurance = assurance;
        this.commission = commission;
        this.taxe = taxe;
        this.totalEcheance = totalEcheance;
        this.soldeCapital = soldeCapital;
        this.capitalRembourse = capitalRembourse;
        this.interetRembourse = interetRembourse;
        this.penaliteReglee = penaliteReglee;
        this.assuranceReglee = assuranceReglee;
        this.commissionReglee = commissionReglee;
        this.taxeReglee = taxeReglee;
        this.statutEcheance = statutEcheance;
        this.version = version;
        this.credit = credit;
    }

    public Long getIdAmortp() {
        return idAmortp;
    }

    public void setIdAmortp(Long idAmortp) {
        this.idAmortp = idAmortp;
    }

    public Integer getNumEcheance() {
        return numEcheance;
    }

    public void setNumEcheance(Integer numEcheance) {
        this.numEcheance = numEcheance;
    }

    public LocalDate getDateEcheance() {
        return dateEcheance;
    }

    public void setDateEcheance(LocalDate dateEcheance) {
        this.dateEcheance = dateEcheance;
    }

    public LocalDate getDateReglement() {
        return dateReglement;
    }

    public void setDateReglement(LocalDate dateReglement) {
        this.dateReglement = dateReglement;
    }

    public BigDecimal getCapital() {
        return capital;
    }

    public void setCapital(BigDecimal capital) {
        this.capital = capital;
    }

    public BigDecimal getInteret() {
        return interet;
    }

    public void setInteret(BigDecimal interet) {
        this.interet = interet;
    }

    public BigDecimal getPenalite() {
        return penalite;
    }

    public void setPenalite(BigDecimal penalite) {
        this.penalite = penalite;
    }

    public BigDecimal getAssurance() {
        return assurance;
    }

    public void setAssurance(BigDecimal assurance) {
        this.assurance = assurance;
    }

    public BigDecimal getCommission() {
        return commission;
    }

    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    public BigDecimal getTaxe() {
        return taxe;
    }

    public void setTaxe(BigDecimal taxe) {
        this.taxe = taxe;
    }

    public BigDecimal getTotalEcheance() {
        return totalEcheance;
    }

    public void setTotalEcheance(BigDecimal totalEcheance) {
        this.totalEcheance = totalEcheance;
    }

    public BigDecimal getSoldeCapital() {
        return soldeCapital;
    }

    public void setSoldeCapital(BigDecimal soldeCapital) {
        this.soldeCapital = soldeCapital;
    }

    public BigDecimal getCapitalRembourse() {
        return capitalRembourse;
    }

    public void setCapitalRembourse(BigDecimal capitalRembourse) {
        this.capitalRembourse = capitalRembourse;
    }

    public BigDecimal getInteretRembourse() {
        return interetRembourse;
    }

    public void setInteretRembourse(BigDecimal interetRembourse) {
        this.interetRembourse = interetRembourse;
    }

    public BigDecimal getPenaliteReglee() {
        return penaliteReglee;
    }

    public void setPenaliteReglee(BigDecimal penaliteReglee) {
        this.penaliteReglee = penaliteReglee;
    }

    public BigDecimal getAssuranceReglee() {
        return assuranceReglee;
    }

    public void setAssuranceReglee(BigDecimal assuranceReglee) {
        this.assuranceReglee = assuranceReglee;
    }

    public BigDecimal getCommissionReglee() {
        return commissionReglee;
    }

    public void setCommissionReglee(BigDecimal commissionReglee) {
        this.commissionReglee = commissionReglee;
    }

    public BigDecimal getTaxeReglee() {
        return taxeReglee;
    }

    public void setTaxeReglee(BigDecimal taxeReglee) {
        this.taxeReglee = taxeReglee;
    }

    public String getStatutEcheance() {
        return statutEcheance;
    }

    public void setStatutEcheance(String statutEcheance) {
        this.statutEcheance = statutEcheance;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Credits getCredit() {
        return credit;
    }

    public void setCredit(Credits credit) {
        this.credit = credit;
    }

    @Override
    public String toString() {
        return "Amortp("
            + "idAmortp=" + idAmortp
            + ", numEcheance=" + numEcheance
            + ")";
    }
}
